export const DISPLAY_ALERT = 'SHOW_ALERT'
export const DISPLAY_ALERT_ID = 'DISPLAY_ALERT_ID'

export const CLEAR_ALERT = 'CLEAR_ALERT'

export const CREATE_PRODUCT_BEGIN = 'CREATE_PRODUCT_BEGIN'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'

export const DELETE_PRODUCT_BEGIN = 'DELETE_PRODUCT_BEGIN'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const GET_PRODUCT_BEGIN = 'GET_PRODUCT_BEGIN'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'